#!/usr/bin/python2
import commands,os
import cgi

port=raw_input("Enter Port Number of Instance: ")
host=raw_input("Enter Host Address: ")
user=raw_input("Enter user name: Ayush ")
p=raw_input("Enter New Password: ")

commands.getstatusoutput("/usr/bin/mysqladmin -u "+ user +" -h "+ host +" -P "+ port +" password "+ p +" ")
